#!/bin/bash
VERSION=0.0.1
if [ $1 = "version" -o $1 = "v" -o $1 = "-v" ]; then
  echo $VERSION

elif [ $1 = "install" -o $1 = "i" ]; then
docker run -it -v $(pwd)/website:/app -w /app -p 1234:1234 node:12-alpine yarn install "$@"

elif [ $1 = "build" ]; then
docker run -it -v $(pwd)/website:/app -w /app -p 1234:1234 node:12-alpine yarn parcel watch src/index.html

fi
